---
collections:
- name: https://opendev.org/openstack/ansible-config_template
  type: git
  version: master
- name: https://opendev.org/openstack/openstack-ansible-plugins
  type: git
  version: master
- name: community.general
  source: https://github.com/ansible-collections/community.general
  type: git
  version: 10.0.1
- name: ansible.mariadb
  source: https://github.com/ansible-collections/ansible.mariadb
  type: git
  version: 6.0.2
roles:
- name: apt_package_pinning
  src: git+https://opendev.org/openstack/openstack-ansible-apt_package_pinning
  version: master
- name: systemd_service
  src: git+https://opendev.org/openstack/ansible-role-systemd_service
  version: master
